<?php

namespace Database\Seeders;

use App\Models\WorkStep;
use Illuminate\Database\Seeder;

class WorkStepsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ["id"=>"1","instruction_id"=>"1","work_step_list_id"=>"1","status_id"=>"1","job_id"=>"2","user_id"=>"2","machine_id"=>null,"target_date"=>"2023-07-25","schedule_date"=>"2023-07-25","target_time"=>null,"step"=>"0","state_task"=>"Running","status_task"=>"Process","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>"2023-07-25 04=>29=>38","selesai"=>"2023-07-25 04=>29=>38","spk_status"=>"Running"],
            ["id"=>"2","instruction_id"=>"1","work_step_list_id"=>"2","status_id"=>"1","job_id"=>"2","user_id"=>"4","machine_id"=>null,"target_date"=>"2023-07-25","schedule_date"=>"2023-07-25","target_time"=>null,"step"=>"1","state_task"=>"Running","status_task"=>"Pending Approved","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>"2023-07-25 04=>29=>38","selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"3","instruction_id"=>"1","work_step_list_id"=>"6","status_id"=>"1","job_id"=>"2","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"2","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"4","instruction_id"=>"1","work_step_list_id"=>"37","status_id"=>"1","job_id"=>"2","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"3","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"5","instruction_id"=>"2","work_step_list_id"=>"1","status_id"=>"1","job_id"=>"5","user_id"=>"2","machine_id"=>null,"target_date"=>"2023-07-25","schedule_date"=>"2023-07-25","target_time"=>null,"step"=>"0","state_task"=>"Running","status_task"=>"Process","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>"2023-07-25 04=>30=>50","selesai"=>"2023-07-25 04=>30=>50","spk_status"=>"Running"],
            ["id"=>"6","instruction_id"=>"2","work_step_list_id"=>"5","status_id"=>"1","job_id"=>"5","user_id"=>null,"machine_id"=>null,"target_date"=>"2023-07-25","schedule_date"=>"2023-07-25","target_time"=>null,"step"=>"1","state_task"=>"Running","status_task"=>"Pending Approved","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>"2023-07-25 04=>30=>50","selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"7","instruction_id"=>"2","work_step_list_id"=>"3","status_id"=>"1","job_id"=>"5","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"2","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"8","instruction_id"=>"2","work_step_list_id"=>"2","status_id"=>"1","job_id"=>"5","user_id"=>"4","machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"3","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"9","instruction_id"=>"2","work_step_list_id"=>"6","status_id"=>"1","job_id"=>"5","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"4","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"10","instruction_id"=>"2","work_step_list_id"=>"37","status_id"=>"1","job_id"=>"5","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"5","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"11","instruction_id"=>"2","work_step_list_id"=>"7","status_id"=>"1","job_id"=>"5","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"6","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"12","instruction_id"=>"2","work_step_list_id"=>"8","status_id"=>"1","job_id"=>"5","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"7","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"13","instruction_id"=>"2","work_step_list_id"=>"10","status_id"=>"1","job_id"=>"5","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"8","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"14","instruction_id"=>"2","work_step_list_id"=>"23","status_id"=>"1","job_id"=>"5","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"9","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"15","instruction_id"=>"2","work_step_list_id"=>"24","status_id"=>"1","job_id"=>"5","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"10","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"16","instruction_id"=>"2","work_step_list_id"=>"35","status_id"=>"1","job_id"=>"5","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"11","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"17","instruction_id"=>"2","work_step_list_id"=>"36","status_id"=>"1","job_id"=>"5","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"12","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"18","instruction_id"=>"3","work_step_list_id"=>"1","status_id"=>"1","job_id"=>"4","user_id"=>"2","machine_id"=>null,"target_date"=>"2023-07-25","schedule_date"=>"2023-07-25","target_time"=>null,"step"=>"0","state_task"=>"Running","status_task"=>"Process","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>"2023-07-25 04=>33=>46","selesai"=>"2023-07-25 04=>33=>46","spk_status"=>"Running"],
            ["id"=>"19","instruction_id"=>"3","work_step_list_id"=>"4","status_id"=>"1","job_id"=>"4","user_id"=>null,"machine_id"=>null,"target_date"=>"2023-07-25","schedule_date"=>"2023-07-25","target_time"=>null,"step"=>"1","state_task"=>"Running","status_task"=>"Pending Approved","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>"2023-07-25 04=>33=>46","selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"20","instruction_id"=>"3","work_step_list_id"=>"5","status_id"=>"1","job_id"=>"4","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"2","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"21","instruction_id"=>"3","work_step_list_id"=>"3","status_id"=>"1","job_id"=>"4","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"3","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"22","instruction_id"=>"3","work_step_list_id"=>"2","status_id"=>"1","job_id"=>"4","user_id"=>"4","machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"4","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"23","instruction_id"=>"3","work_step_list_id"=>"6","status_id"=>"1","job_id"=>"4","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"5","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"24","instruction_id"=>"3","work_step_list_id"=>"37","status_id"=>"1","job_id"=>"4","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"6","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"25","instruction_id"=>"3","work_step_list_id"=>"7","status_id"=>"1","job_id"=>"4","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"7","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"26","instruction_id"=>"3","work_step_list_id"=>"8","status_id"=>"1","job_id"=>"4","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"8","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"27","instruction_id"=>"3","work_step_list_id"=>"10","status_id"=>"1","job_id"=>"4","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"9","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"28","instruction_id"=>"3","work_step_list_id"=>"23","status_id"=>"1","job_id"=>"4","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"10","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"29","instruction_id"=>"3","work_step_list_id"=>"24","status_id"=>"1","job_id"=>"4","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"11","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"30","instruction_id"=>"3","work_step_list_id"=>"34","status_id"=>"1","job_id"=>"4","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"12","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"31","instruction_id"=>"3","work_step_list_id"=>"35","status_id"=>"1","job_id"=>"4","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"13","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"],
            ["id"=>"32","instruction_id"=>"3","work_step_list_id"=>"36","status_id"=>"1","job_id"=>"4","user_id"=>null,"machine_id"=>null,"target_date"=>null,"schedule_date"=>null,"target_time"=>null,"step"=>"14","state_task"=>"Not Running","status_task"=>"Waiting","timer"=>null,"alasan_pause"=>null,"catatan_proses_pengerjaan"=>null,"reject_from_id"=>null,"reject_from_status"=>null,"reject_from_job"=>null,"task_priority"=>"Normal","dikerjakan"=>null,"selesai"=>null,"spk_status"=>"Running"]
            

        ];
        foreach ($data as $workStep) {
            WorkStep::create($workStep);
        }
    }
}
